### ISSUE TITLE
Stop parsing inventory as a jinja2 template and leave it as an ansible parseable file

### ISSUE THREAD

**Issue by fgiorgetti** [rh-messaging-qe/iqa_testsuite#6]

**Comment by fgiorgetti** [comment]
Working on it.

**Comment by fgiorgetti** [comment]
I have submitted a PR for this.
After we get it merged into devel, @enkeys will need to rebase your branch on top of devel and adjust your inventory files, before submitting a PR.
Once applied to devel, this can be closed.

**Comment by lenosi** [comment]
👍 to solution "-e cli_arg=value" PR #7 was merged to devel. I going to rebase my branch now.
